### ISSUE TITLE
Lower case typo

### ISSUE THREAD

**Issue by Foryah** [standardebooks/leo-tolstoy_a-confession_aylmer-maude#1]
There's a lower case typo [here](https://github.com/standardebooks/leo-tolstoy_a-confession_aylmer-maude_louise-maude/blob/master/src/epub/text/chapter-2.xhtml#L19), in Chapter 2. I believe the 'and' is suppose to use capital letter.

> [...] and you teach wrongly. and they disputed, quarrelled, [...]

**Comment by acabal** [comment]
Not sure how I missed this issue, sorry about that, it's been fixed now!

**Comment by Foryah** [comment]
Don't worry. Not sure it was a issue to begin with... I've seen this in a bunch of places in the book and in other older books as well. My hypothesis is that it was considered correct back in the day when those books were written :)
