### ISSUE TITLE
missing word

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/leo-tolstoy_a-confession_aylmer-maude#12]
https://github.com/standardebooks/leo-tolstoy_a-confession_aylmer-maude/blob/28db536c9cd318dae9d07fe2533ceac0a32125ce/src/epub/text/chapter-12.xhtml#L26

"...past hidden from, has produced..." should be "...past hidden from **me**, has produced..."

**Comment by acabal** [comment]
Thanks, this should be fixed now!
