### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by siiky** [standardebooks/leo-tolstoy_a-confession_aylmer-maude#8]
On top of the changes I proposed on #7 I have a few other questions. I'm mostly looking for another opinion. It seems I can't see the scans at https://catalog.hathitrust.org/Record/008973972 but maybe it's possible to confirm these there.

### XI

> Evidently he could not other reply to that question than that life is the greatest evil, ...

"could not other reply" doesn't sound good to me.

### Afterword

> But not to look was still worse, for I thought of what would happen to me directly I fell from the last support.

It seems something is missing here, but I can't be sure what.

> And then, as happens in dreams, I imagined the mechanism by means of which I was held; a very natural intelligible, and sure means, though to one awake that mechanism has no sense.

Same here. Maybe a comma between "natural" and "intelligible"?

**Comment by acabal** [comment]
The 2nd is not a typo but the rest are. Thanks for catching them!
